# Introduction to `pandas` 🐼

All credits to Dr. Musashi Hinck ([Original GitHub Repo](https://github.com/634dev/ds3-intro-python/tree/main)).

##Main pros

- Popular library for analyzing **tabular data**
	- Tabular: rectangular, has rows and columns.
- _Expressive_ and _full-featured_
	- Readable syntax
	- Lots of built-in functions
	- can handle hierarchical indexing
- Support for **many** file types


## Main cons
- Struggles with larger datasets (>1M rows)
- Significant overhead
- Memory-intensive
- **CPU-only**

## Alternative libraries

-  `dask`:
  - **Advantages**:
    - Parallelized dataframes
    - Integration with `pandas` and `numpy`.
    - implemented purely in Python
  - **Disadvantages**:
    - Objects are immutable, and don't support inplace operations
	- Significant improvements only with large datasets
- `GeoPandas`:
  - **Advantages**:
    - Better handling of geographic data (e.g. distance measures).
    - Seamless integration with geovisualisation libraries (e.g. `folium`).
  - **Disadvantages**:
    - Slow, only meaningful for small geo-dataframes.
- `datasets`:
  - **Advantages**:
    - Hugging-Face dataset library: innate compatibility with `transformers`
    - Has a repository of datasets for code testing
  - **Disadvantages**:
    - Not suitable for data wrangling & visualisation.
		- Not as extensively implemented as `tensorflow.data.Dataset`or `torch.utils.data.Dataset`.


If you want to parallelize a preprocessing task, try using multiprocessing library.

## Running Scenario

- Analyzing student scores and sending summary reports
- Two datasets:
	- `data/scores.csv`: students' scores in 5 subjects
	- `data/contacts.csv`: students' contact details

## Functionality Covered

- How do I read in data from files?
- How do I select and filter values?
- How do I perform calculations on data?
- How do I merge/combine data from multiple sources?

# Importing Libraries

_A brief aside on a first step that tends to get overlooked._

## Libraries

- Functionality of base Python is limited for data analysis workflow
- Python language is extensible, benefits from enormous ecosystem
- `pandas` is a _library_ for data analysis

## `import`

- To use a library, we need to `import` it:

In [ ]:
import pandas as pd

df = pd.DataFrame()

- In Jupyter, we can use `%who` to list objects in the global namespace

In [ ]:
%who

df	 pandas	 pd

- The methods within pandas are now accessible as _methods_ of the imported _module_.

In [ ]:
pandas.__version__

'2.1.4'

## `from`

- We can use the `from` command to import objects and methods directly from modules into the global namespace.

In [ ]:
from pandas import __version__
print(__version__)

2.1.4

## `as`

- The default approach in Python is to keep fewer objects in the global namespace.
- This means always prefacing the function or class we want to use with the prefix name.
- This can get verbose, so we often abbreviate library names with `as`:

In [ ]:
import pandas as pd
print(pd)
print(pd.DataFrame)

<module 'pandas' from '/usr/local/lib/python3.10/dist-packages/pandas/__init__.py'>
<class 'pandas.core.frame.DataFrame'>

## Contrast with `R`

- In `R`, the default approach is to import all methods from a library into the global namespace.
- If we did this with `pandas` it would look like this:

In [ ]:
from pandas import *
%who

## Cleanup

In [ ]:
%reset -f

In [ ]:
import pandas as pd # normal way of importing

In [ ]:
# For colab: we need to replace paths to files with urls to the location on github
data_url = "https://raw.githubusercontent.com/mmjh-dev/ds3-intro-python/main/"

# Getting Your Data

## Manual `DataFrame`

- Can be constructed manually from a `dict` of equal-length `list`s.

In [ ]:
scores_dict = {
	'student_id': ['5a01', '5a12', '5b05', '5b10', '5e04'],
	'math':    [95, 78, 85, 90, 88],
	'english': [97, 91, 86, 89, 90],
	'history': [80, 89, 94, 87, 85],
	'biology': [81, 86, 88, 99, 88],
	'art':     [86, 81, 82, 91, 84]
}

## Manual `DataFrame`

In [ ]:
df = pd.DataFrame(data=scores_dict)
df

  student_id  math  english  history  biology  art
0       5a01    95       97       80       81   86
1       5a12    78       91       89       86   81
2       5b05    85       86       94       88   82
3       5b10    90       89       87       99   91
4       5e04    88       90       85       88   84

## Reading from a file

`pandas` comes with functions for reading and writing to all kinds of data formats. A quick list can be viewed using tab completion:

In the cell below, type `pd.read_` and then press the \<TAB\> key

## Data IO: `read_csv`

In [ ]:
df = pd.read_csv(data_url+"data/scores.csv")
df

  student_id  math  english  history  biology  art
0       5a01    95       97       80       81   86
1       5a12    78       91       89       86   81
2       5b05    85       86       94       88   82
3       5b10    90       89       87       99   91
4       5e04    88       90       85       88   84

# Selecting Data

- "What were everyone's `math` scores?"
- "What did student `5a12` get on all subjects?"
- "What did `5a12` and `5e04` get on `history` and `art`?"

## Columns and Index

- Entries indexed by columns and rows

In [ ]:
df

## `df.columns` and `df.index`

- These can be accessed through following:

In [ ]:
df.columns

In [ ]:
df.index

- By default dataframes have a numerical index.

## Setting the Index

- `df.set_index()` returns dataframe with new index

In [ ]:
df = df.set_index('student_id')
df.index

In [ ]:
df

## `.loc`

- Use `.loc` for name-based indexing.
- General syntax: `.loc[<INDEX>, <COLS>]`
	- `<INDEX>` and `<COLS>` correspond to the index and column names.
	- They can be a single value, a list, or `:` to indicate "all".
- Let's learn by example:

## Row

- "What did `5a01` get on all (`:`) exams?"

In [ ]:
df.loc['5a01', :]

In [ ]:
from IPython.display import HTML
HTML(data_url+"figures/pandas_loc_row.html")

## Column

- "What did everyone (`:`) get on `history`?"

In [ ]:
df.loc[:, 'history']

In [ ]:
HTML(data_url+"figures/pandas_loc_col.html")

## Multiple Rows

- "What did `5a01` and `5a12` (`['5a01', '5a12']`) get on all (`:`) exams?"

In [ ]:
df.loc[['5a01', '5a12'], :]

In [ ]:
HTML(data_url+"figures/pandas_loc_multi_row.html")

In [ ]:
from multiprocessing.pool import ThreadPool

In [ ]:
d = {'Animal': [0,0,1,1], 'weight': [1,2,3,4]}
df = pd.DataFrame.from_dict(d)

In [ ]:
groups = [group for animal, group in df.groupby('Animal')]

with ThreadPool(10) as pool:
  results = pool.map(lambda x: x+1, groups)

TypeError: ignored

In [ ]:
results

[   Animal  weight
 0       1       2
 1       1       3,
    Animal  weight
 2       2       4
 3       2       5]

## Multiple Columns

- What did everyone (`:`) get on `art` and `history` (`['art', 'history']`)?

In [ ]:
df.loc[:, ['art', 'history']]

In [ ]:
HTML(data_url+"figures/pandas_loc_multi_col.html")

## Label Order

Note the order of labels changes the order of columns:

In [ ]:
df.loc[:, ['art', 'history']]

## Cell

- What did `5a01` get in `history`?

In [ ]:
df.loc['5a01', 'history']

In [ ]:
HTML(data_url+"figures/pandas_loc_cell.html")

## Multiple Values

- What did `5a01` get in `history` and `art`?

In [ ]:
df.loc['5a12', ['history', 'art']]

In [ ]:
HTML(data_url+"figures/pandas_loc_multi1.html")

## cont.

- What did `5a01`, `5a12`, and `5b05` get in `biology` and `art`?

In [ ]:
df.loc[['5a01', '5a12', '5b05'], ['biology', 'art']]

In [ ]:
HTML(data_url+"figures/pandas_loc_multi2.html")

## Filtering

"The overall scores of students who got _90 or higher in math_""

- Create a _boolean array_

In [ ]:
df[df.loc[:, 'math'] >= 90]

## `.loc` Filtering

- `.loc` can take boolean arrays:

In [ ]:
good_math = df.loc[:, 'math'] >= 90
df.loc[good_math, :]

- Shorter syntax:

In [ ]:
df.loc[df['math'].ge(90), :]

## Combining Indexers and Filters

- `history` scores where `math` and `art` $>=$ 85

In [ ]:
df.loc[(df.loc[:, 'math']>=85) &
	   (df.loc[:, 'art']>=85),
	   'history']

## `.iloc`: locational indexing

- First 2 rows (`:2` in Python)
- Last 3 columns (`-3:`)

In [ ]:
df.iloc[:2, -1]

# Operations

- "Is this score over 90?"
- "What was the average `math` score?"
- "What was `5b10`'s maximum score?""
- "What was the lowest score in each exam?"

## Some Terminology

Clarifying what I mean in this lecture when I say:

- _Scalar_: a single value
- _Non-scalar_: a data structure capable of containing multiple data points
- _Argument(s)_: the input(s) to a function

## `Series` and `DataFrame`

- `pd.Series` are 1-dimensional
- `pd.DataFrame` are 2-dimensional

## `Series`

- Passing a scalar to an indexer (`.loc`) on a `DataFrame` returns a `Series`

In [ ]:
df[0].str.split(" ")

## `DataFrame`

- Passing a `list` returns a `DataFrame`

In [ ]:
df.iloc[:, :1]

## Arguments at Three Levels

- Scalar: "Is this score over 90?"

In [ ]:
def greater_than_90(x):
	return x > 90

- Series: "What is the maximum score on one exam?"

In [ ]:
def maximum(scores):
	return max(scores)

- Dataframe: "How many individual scores?"

In [ ]:
def how_many_elements(df):
	rows, cols = df.shape
	return rows*cols

## Convenience Functions

- `Series` and `DataFrame` objects have many common operations built-in:
  - $\ne$ (`.ne()`), $\gt$ (`.gt()`), ...
  - mean (`.mean()`), median (`.median()`), standard deviation (`.std()`), ...
- These tend to be optimized.
- See [documentation](https://pandas.pydata.org/docs/user_guide/basics.html#descriptive-statistics) for list.

## "What was the average `math` score?"

In [ ]:
df.loc[:, 'math'].mean()

## `apply` and `applymap`

- Custom functions can be applied to `Series` and `DataFrame`s using their `.apply` method.
- `pd.Series.apply`: functions with _scalar arguments_
- `pd.DataFrame.apply`: functions with `pd.Series` as an argument
	- Specify `axis`: 0 is row-wise, 1 is column-wise
- `pd.DataFrame.applymap`: functions with _scalar arguments_

## "What was the lowest score for each exam and student??"

- Lowest per exam (`axis=0`)

In [ ]:
df.min(axis=0)

- Lowest per student (`axis=1`, using built-in `min`):

In [ ]:
df.apply(min, axis=1)

## Convert Scores to A-F Ranking

In [ ]:
def convert_score(x):
	score = ''
	if x >= 90:
		score = 'A'
	elif x >= 80:
		score = 'B'
	elif x >= 70:
		score = 'C'
	elif x >= 60:
		score = 'D'
	else:
		score = 'F'
	return score

## Convert Scores to A-F Ranking

In [ ]:
df.applymap(convert_score)

# Combining Data

- How do we combine data from multiple sources?

## Two Ways

- Concatenating: sticking it together
- Joining: merging on common "key"

## We forgot two students!

In [ ]:
df_extra = pd.read_csv(data_url+'data/scores_extra.csv',
					   index_col='student_id')
df_extra

## Concatenation

In [ ]:
pd.concat([df, df_extra], axis=0)

## Different Columns

- `.reset_index()` moves the index into a column:

In [ ]:
df_extra.reset_index()

## Different Columns

- Concatenating with different columns creates NA values:

In [ ]:
pd.concat([df_extra, df_extra.reset_index()])

## Contact Details

- We want to match scores to students' first names

In [ ]:
pd.read_csv(data_url+'data/contacts.csv')

## Preparing data for joining

- The two dataframes have one column in common: the student ID.
	- In one it's `StudentID`, in the other `student_id`.
- For visual simplicity, I move `student_id` back to the columns

In [ ]:
df_contact = pd.read_csv(data_url+'data/contacts.csv')
df_scores = df.reset_index()

## Key

- Note that the two dataframes do not have the exact same values of student ID!

In [ ]:
df_contact['StudentID']

In [ ]:
df_scores['student_id']

## Merge Syntax

In [ ]:
pd.merge(
	how=<inner/left/right/outer>
	left=df_contact[['FirstName', 'StudentID']],
	right=df_scores[['student_id', 'history']],
	left_on='StudentID',
	right_on='student_id')

- We specify the two dataframes as `left` and `right`
- We specify the common key for each dataframe
	- Note if they were the same, we could use the argument `on`
- `how` is easiest to explain visually

## `how='inner'`

In [ ]:
pd.merge(
	how='inner',
	left=df_contact[['FirstName', 'StudentID']],
	right=df_scores[['student_id', 'history']],
	left_on='StudentID',
	right_on='student_id')

## `how='left'`

In [ ]:
pd.merge(
	how='left',
	left=df_contact[['FirstName', 'StudentID']],
	right=df_scores[['student_id', 'history']],
	left_on='StudentID',
	right_on='student_id')

## `how='right'`

In [ ]:
pd.merge(
	how='right',
	left=df_contact[['FirstName', 'StudentID']],
	right=df_scores[['student_id', 'history']],
	left_on='StudentID',
	right_on='student_id')

## `how='outer'`

In [ ]:
pd.merge(
	how='outer',
	left=df_contact[['FirstName', 'StudentID']],
	right=df_scores[['student_id', 'history']],
	left_on='StudentID',
	right_on='student_id')

# Exploratory Analysis

## British Election Study Data

In [ ]:
bes_df = pd.read_csv(data_url+'data/bes_data.csv')

## First-Look Functions

- When working with data, your first step should always be _getting to know the data_
	- Manually inspect samples of the data.
	- Check dimensions: are they expected?
	- Check data types: are they expected?
	- Tabulate variables: what are the levels?

## Inspect first 5 rows

In [ ]:
bes_df.head()

,voted,tory_vote,election_interest,civic_duty,party_id,ideo_lr,ideo_pc1,ideo_pc2,vote_leave,class,female,edlevel,region
0,1,0,1,1,Labour,3,-1.204655,1.158077,1,2,1,0,East Midlands
1,1,0,1,5,Labour,0,3.077969,1.322138,0,2,0,1,East Midlands
2,0,0,2,2,Refused,5,-0.634762,-4.671532,1,2,0,0,East Midlands
3,1,0,1,4,Labour,6,3.686122,1.205449,1,2,1,0,East Midlands
4,1,0,1,4,Labour,2,0.139499,1.408508,0,2,1,4,East Midlands

## What are the dimensions of the dataset?

In [ ]:
bes_df.shape

## What data types are each of the columns?

In [ ]:
bes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   voted              2194 non-null   int64
 1   tory_vote          2194 non-null   int64
 2   election_interest  2194 non-null   int64
 3   civic_duty         2194 non-null   int64
 4   party_id           2194 non-null   object
 5   ideo_lr            2194 non-null   int64
 6   ideo_pc1           2194 non-null   float64
 7   ideo_pc2           2194 non-null   float64
 8   vote_leave         2194 non-null   int64
 9   class              2194 non-null   int64
 10  female             2194 non-null   int64
 11  edlevel            2194 non-null   int64
 12  region             2194 non-null   object
dtypes: float64(2), int64(9), object(2)
memory usage: 223.0+ KB

## What unique values do each column contain?

- `pd.Series.value_counts()` for tabulation

In [ ]:
bes_df['female'].value_counts()

female
1    1193
0    1001
Name: count, dtype: int64

In [ ]:
bes_df['region'].value_counts()

# Recap

## `pandas`

- File I/O (reading/writing data formats)
- Indexing, slicing, filtering
- Operations on data
- Combining/merging data
- Exploratory look

# Additional Resources

## Textbook

The following sections of _Python for Data Analysis: Data Wrangling with Pandas, NumPy and IPython, 2nd edition_ are relevant to this lecture:

- 5.*: Getting Started with pandas
- 6.*: Data Loading, Storage and File Formats
- 7.1-2: Data Cleaning and Preparation
- 7.3: String Manipulation
- 12.1: Categorical Data

## Blogs, Docs

- [`pandas` guide to combining dataframes](https://pandas.pydata.org/docs/user_guide/merging.html)
- Pandas Data: https://pbpython.com/pandas_dtypes.html